---
- name: Create a directory if it does not exist
  file:
    path: "{{ SentryDirectoryPath }}"
    state: directory
    mode: '0755'

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{ SentryURL }}"
    dest: "{{ SentryDirectoryPath }}"
    remote_src: yes   

- name: Running install.sh  
  command: bash install.sh --no-user-prompt 
  args:
    chdir: "{{ SentryDirectoryPath }}self-hosted-22.6.0"


    
- name: Generic question with multiple different responses
  expect:
    command: sudo docker-compose run --rm web createuser
    echo: true
    responses:
      'Email:': "{{ EmailId }}"
      'Password:': "{{ password }}"
      'Repeat for confirmation:': "{{ password }}"
      'Should this user be a superuser?(.*)': "{{ SuperUser }}"
      'Should this user have Super Admin role?(,*)': "{{ SuperAdmin }}"
    chdir: "{{ SentryDirectoryPath }}/self-hosted-22.6.0/"
    timeout: 1200

- name: Setting up sentry
  command: sudo docker-compose up -d
  args:
    chdir: "{{ SentryDirectoryPath }}self-hosted-22.6.0"